### ISSUE TITLE
have to press ctrl-j instead of RETURN

### ISSUE THREAD

**Issue by hlindberg** [puppetlabs/ticketmatch#2]
When answering the questions I have to press ctrl-j to get a newline instead of pressing RETURN key.

**Comment by GabrielNagy** [comment]
might have been some issues with your terminal, I get those from time to time as well but it's not application dependent... `reset` or `stty sane` should bring it back

**Comment by hlindberg** [comment]
There was no issue with my terminal - it worked just fine both before and after running ticketmatch. I would not have logged this ticket otherwise.

**Comment by GabrielNagy** [comment]
Then it might have stemmed from [JEG2/highline](https://github.com/JEG2/highline) which is the library ticketmatch uses for interactive input/output. Either way, I cannot find a way to reproduce. Does this still happen for you?

**Comment by hlindberg** [comment]
Don't know have not used it since I reported this - keep the ticket closed, will report again if it happens...
